import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Carousel from '../components/carousel'
import Colors from '../components/colors'
import Description from '../components/description'

const Footer = dynamic(
  () => import('../components/footer'),
  { ssr: false }
)
import Header from '../components/header'

const NewLetter = dynamic(
  () => import('../components/newslatter'),
  { ssr: false }
)


const Products = dynamic(
  () => import('../components/Products'),
  { ssr: false }
)

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Carousel/>
      <Products/>
      <Description/>
      <Description rtl={false}/>
      <Description/>
      <Description rtl={false}/>
      <NewLetter/>
      <Footer/>
    </div>
  )
}
